name: CI

on:
  - push
  - pull_request

env:
  CI: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v7
      - name: Set up Node
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: yarn
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build
      - name: Lint
        run: yarn lint
      - name: Check style
        run: yarn check-style
